// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxuqcahcrahimxnawutl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4dXFjYWhjcmFoaW14bmF3dXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MjEyNzMsImV4cCI6MjA3MTQ5NzI3M30.WOpCL3zd99vMxSWI6uvUmJydWPZqCSAYIYjCmrp3f1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});